include: package:flutter_lints/flutter.yaml 
 
analyzer: 
  exclude: 
    - "**/*.g.dart" 
    - "**/*.freezed.dart" 
    - "**/*.mocks.dart" 
  errors: 
    missing_required_param: warning 
    unused_import: ignore 
    unused_element: ignore 
    unused_local_variable: ignore 
    missing_return: warning 
    invalid_annotation_target: ignore 
 
linter: 
  rules: 
    avoid_print: false 
    prefer_const_constructors: false 
    use_key_in_widget_constructors: false 
    library_private_types_in_public_api: false 
